#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import shutil
import sys

from doodbalib import (
    addons_config,
    CLEAN,
    CORE_DIR,
    is_inside,
    logger,
    ODOO_DIR,
    SRC_DIR,
)

if not CLEAN:
    logger.warning("Not cleaning garbage")
    sys.exit()

addon_paths = [
    os.path.realpath(os.path.join(SRC_DIR, repo, addon))
    for addon, repo in addons_config(False)]
for directory, subdirectories, subfiles in os.walk(SRC_DIR, False):
    # Skip odoo source code
    if is_inside(directory, ODOO_DIR) and not is_inside(directory, CORE_DIR):
        continue
    # Skip addons enabled in addons.yaml
    for addon_path in addon_paths:
        if is_inside(directory, addon_path):
            continue
    # Remove every other directory
    logger.info("Removing directory %s", directory)
    shutil.rmtree(directory)
